-- create raw data and processed data tables
CREATE TABLE products_csv (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  name text,
  slogan text,
  description text,
  category text,
  default_price money
);

CREATE TABLE products (
id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
name text
);

CREATE TABLE questions_csv (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id int references products_csv(id),
  body text,
  date_written bigint,
  asker_name text,
  asker_email text,
  reported smallint,
  helpful int
);

CREATE TABLE questions (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id int references products(id),
  body varchar(1000),
  date_written timestamp,
  asker_name varchar(50),
  asker_email varchar(62),
  reported smallint,
  helpful int
);

CREATE TABLE answers_csv (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  question_id int references questions_csv(id),
  body text,
  date_written bigint,
  answerer_name text,
  answerer_email text,
  reported smallint,
  helpful int
);

CREATE TABLE answers (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  question_id int references questions(id),
  body varchar(1000),
  date_written timestamp,
  answerer_name varchar(50),
  answerer_email varchar(62),
  reported smallint,
  helpful int
);

CREATE TABLE photos_csv (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  answer_id int references answers_csv(id),
  url text
);

CREATE TABLE photos (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  answer_id int references answers(id),
  url varchar(2083)
);

-- add CSV data to raw data tables
COPY products_csv(id, name, slogan, description, category, default_price)
FROM '/Users/samanthapham/Documents/hack_reactor/sdc-samantha/product.csv'
DELIMITER ','
CSV HEADER;

COPY questions_csv(id, product_id, body, date_written, asker_name, asker_email, reported, helpful)
FROM '/Users/samanthapham/Documents/hack_reactor/sdc-samantha/questions.csv'
DELIMITER ','
CSV HEADER;

COPY answers_csv(id, question_id, body, date_written, answerer_name, answerer_email, reported, helpful)
FROM '/Users/samanthapham/Documents/hack_reactor/sdc-samantha/answers.csv'
DELIMITER ','
CSV HEADER;

COPY photos_csv(id, answer_id, url)
FROM '/Users/samanthapham/Documents/hack_reactor/sdc-samantha/answers_photos.csv'
DELIMITER ','
CSV HEADER;

-- insert transformed raw data into processed data tables
INSERT INTO products (id, name)
SELECT id, name
FROM products_csv;


INSERT INTO questions (id, product_id, body, date_written, asker_name, asker_email, reported, helpful)
SELECT id, product_id, body, to_timestamp(date_written / 1000), asker_name, asker_email, reported, helpful
FROM questions_csv;

ALTER TABLE questions
ALTER COLUMN reported TYPE boolean
USING CASE WHEN reported = 0 THEN FALSE
WHEN reported = 1 THEN TRUE
ELSE NULL
END;

INSERT INTO answers (id, question_id, body, date_written, answerer_name, answerer_email, reported, helpful)
SELECT id, question_id, body, to_timestamp(date_written / 1000), answerer_name, answerer_email, reported, helpful
FROM answers_csv;

ALTER TABLE answers
ALTER COLUMN reported TYPE boolean
USING CASE WHEN reported = 0 THEN FALSE
WHEN reported = 1 THEN TRUE
ELSE NULL
END;

INSERT INTO photos (id, answer_id, url)
SELECT id, answer_id, url
FROM photos_csv;